# Generated by Django 4.2.4 on 2023-08-29 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0002_remove_course_description_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='course_code',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
